
spring:
  application:
    name: eureka-server
server:
  port: 7002
eureka:
  instance:
    hostname: peer1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer2:7003/eureka/